builds:
  - binary: "pm-creds"
    id: "pm-creds"
    main: "./pm-creds"
    goos:
      - "windows"
      - "linux"
    goarch:
      - "amd64"
      - "386"

  - binary: "pm-creds"
    id: "pm-creds-macos-amd64"
    main: "./pm-creds"
    goos:
      - "darwin"
    goarch:
      - "amd64"

  - binary: "pm-creds"
    id: "pm-creds-macos-arm64"
    main: "./pm-creds"
    goos:
      - "darwin"
    goarch:
      - "arm64"

archives:
  - id: "pm-creds"
    format: "zip"
    replacements:
      amd64: "x64"
      386: "x86"
      darwin: "macOS"
