name: "pull requests"

on:
  pull_request:
    branches:
      - "master"

jobs:
  go-test:
    name: "go test"
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"
    - run: "go test ./..."
