name: "release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
      - name: "setup go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.16"
      - name: "run tests"
        run: "go test ./..."
      - name: "build"
        run: "./build.sh"
      - name: "archive artifacts"
        uses: "actions/upload-artifact@v2"
        with:
          path: "dist"