name: "release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: "release"
    runs-on: "macos-11.0"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "setup go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.16"
      - name: "releaser"
        uses: "goreleaser/goreleaser-action@v2"
        with:
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AC_APPID: "${{ secrets.AC_APPID }}"
      - name: "notarize"
        run: |
          xcrun altool --notarize-app --primary-bundle-id 'se.execit.pm-creds' -u '${{ secrets.AC_USERNAME }}' -p '${{ secrets.AC_PASSWORD }}' -t osx -f ./dist/pm-creds_*_macOS_amd64.zip
          xcrun altool --notarize-app --primary-bundle-id 'se.execit.pm-creds' -u '${{ secrets.AC_USERNAME }}' -p '${{ secrets.AC_PASSWORD }}' -t osx -f ./dist/pm-creds_*_macOS_arm64.zip
